### ISSUE TITLE
NetworkOnMainThread Exception

### ISSUE THREAD

**Issue by sidzi** [niqdev/ipcam-view#18] opened 2016-09-28 13:09 UTC
```
if (mjpegView.isStreaming()) {
                mjpegView.stopPlayback();
            }
```

causes the exception and cannot be called in async task or any other worker thread i.e. has to be called from the UI thread :( , How to fix this ?

**Comment by niqdev** [comment] 2016-09-28 19:30
Hi! Can you please give me more details about the stacktrace and tell me the exact steps for reproduce the error? Thanks

**Comment by sidzi** [comment] 2016-09-29 08:13
yeah sure,
I have to close/stop mjpegView after I press the back button in the activity i.e. in the ```onBackPressed()``` method and so I have to run this code 
```
@Override
    public void onBackPressed() {
            if (mjpegView.isStreaming()) {
                mjpegView.stopPlayback();
            }
        super.onBackPressed();
    }
```
but this gives me an exception , since I cannot do network ops on the main UI thread (which the ```isStreaming()``` function is probably doing) , so what should I do ?

**Comment by niqdev** [comment] 2016-09-29 12:28
I understood now, the real problem is in the [implementation](https://code.google.com/archive/p/android-camera-axis) that this library wrap and the Thread management.
I would suggest to fork the project, add your code on a separate branch and try to debug [MjpegViewDefault](https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/java/com/github/niqdev/mjpeg/MjpegViewDefault.java). In this way I will be able to help you and fix the issue.
Actually `isStreaming()` is at line 330 and doesn't seem to be the problem, maybe `stopPlayback()`.
Thanks

**Comment by sidzi** [comment] 2016-10-19 10:19
really sorry for the delay.
I tried running the forked project and found that the exception was occurring at line 221 in MjpegViewDefault.
```
if (mIn != null) {
            try {
                mIn.close(); /* This line */
            } catch (IOException e) {
            }
            mIn = null;
        }
```
Should the ```mIn.close``` be in a different worker thread ?

**Comment by niqdev** [comment] 2016-10-19 17:47
no problem, can you please push the branch with the implementation on your remote?

Moreover, can you please try to downgrade the library to previous [versions](https://bintray.com/niqdev/maven/mjpeg-view) one by one and see if you have the same problem? I checked the commit and I wouldn't that we have introduced some regressions

Thanks

**Comment by niqdev** [comment] 2016-10-24 18:57
Hi @sidzi , do you still have the problem? Did you try to downgrade the library one by one?
Thanks

**Comment by niqdev** [comment] 2016-10-24 21:44
@sidzi I'm investigating your error, I have it only on old android versions like 18, not on the latest, that's why I wasn't able to reproduce it.
I'm trying to debugging this
```java
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                if (mjpegView.isStreaming()) {
                    mjpegView.stopPlayback();
                }
                break;
        }
        return true;
    }
```
Can you just confirm please your sdk version with the error?
Thanks

**Comment by niqdev** [comment] 2016-10-25 12:43
Links to similar issue
* http://stackoverflow.com/questions/25069186/invalid-address-passed-to-dlfree
* http://stackoverflow.com/questions/13196013/why-application-is-dying-randomly
* http://stackoverflow.com/questions/10662446/invalid-heap-address-and-fatal-signal-11
mostly due to the underling native C code :cold_sweat:

**Comment by sidzi** [comment] 2016-10-26 13:56
I wasn't able to solve the issue , I am running android 6.0.1 (api 23) 
I will look through the links you have posted and tell you if I find anything .

**Comment by danieltigse** [comment] 2016-11-12 23:32
I have the same issue on my samsung galaxy s6 running android 6.0.1

**Comment by niqdev** [comment] 2016-11-13 13:06
@sidzi  and @danieltigse couple of weeks ago I tried to update the UI on this unstable [branch](https://github.com/niqdev/ipcam-view/tree/feature/new-ui) but I gave up, I wasted to much time trying to debug and fix this issue.
At this point the only thing to do probably is to refactor or better rewrite from scratch
* [MjpegViewDefault](https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/java/com/github/niqdev/mjpeg/MjpegViewDefault.java)
* [MjpegInputStreamDefault](https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/java/com/github/niqdev/mjpeg/MjpegInputStreamDefault.java)

because all the issues are mainly related to the underlying implementation.
If you fill brave enough you are free to fork the repo and make the changes on a new branch, otherwise I will try to do it soon or later

**Comment by sidzi** [comment] 2016-11-14 17:55
@niqdev I don't know if I have enough knowledge to do this myself , but if you'd like to , I can pair program with you whenever you decide to work on it , if that helps :)

**Comment by danieltigse** [comment] 2016-11-14 19:23
My only workaround is use the 0.3.4 version, the only version where the stopPlayback method works. And the trick is that when I want to play again I remove and create the view again.

**Comment by niqdev** [comment] 2016-11-14 20:17
Thanks @danieltigse for point out the version.
By the way all changes from `0.3.x` up to the latest are all related to the same problem.
I would definitely like to rewrite it anyway in future!

**Comment by niqdev** [comment] 2017-01-14 13:17
Hi @danieltigse   and @sidzi  , I just published version `0.4.0` to solve and issue to manage multiple view in the same activity. Could you please tell me if with the new version you still have the same problems?
Thanks

**Comment by PhanPirang** [comment] 2017-01-17 01:21
Hi @niqdev, for version 0.4.0, the app still is still crush when I call stopPlayback() method!

**Comment by PhanPirang** [comment] 2017-01-17 01:38
Hi @niqdev, now I can use stopPlayback() method. Thanks for your hard working! Anyway I have another problem when I call freeCameraMemory in OnDestroy method, the app crushed!

**Comment by niqdev** [comment] 2017-01-18 13:00
@PhanPirang yes, is not supported, here is the implementation
```java
@Override
public void freeCameraMemory() {
  throw new UnsupportedOperationException("not implemented");
}
```
Actually this method is there only because the initial plan was to wrap also the native library

**Comment by niqdev** [comment] 2017-01-18 13:02
Since it seems to work now I will close the issue and update also the app soon.
Feel free to re-open the issue or create a new one if have other problems

**Closed by niqdev** 2017-01-18 13:02 UTC
Labels: bug

**Comment by niqdev** [comment] 2017-01-18 13:09
@sidzi @danieltigse @PhanPirang If you are working on an open source project, would you be interested to add in the Readme the link to your app?

**Comment by sidzi** [comment] 2017-01-18 13:54
No , I wasn't , and thank you for the effort :+1:
